name:                KindaC
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/surcher#readme
license:             BSD3
author:              Big Bobby
maintainer:          example@example.com
copyright:           2023 Big Bobby
category:            Console
extra-source-files:
- README.md


dependencies:
  - base >= 4.7 && < 5
  - recursion-schemes
  - data-fix
  - transformers
  - containers
  - megaparsec
  - parser-combinators
  - deriving-compat
  - bifunctors
  - process
  - text
  - prettyprinter  # I wanted to throw out pretty printer, but it simplifies nesting. Since CPrinter does not use that pretty printer, I might be able to generalize that one to be used for printing (they are pretty similar, so... yknow).
                   # but then I might as well download a dependency kek

  # https://discourse.haskell.org/t/recompilation-issue-with-stack-test/10120/11
  # Test packages. The thing is, when they are only in `tests`, it triggers recompilation, which is slow.

  - hspec
  - text
  - directory
  - temporary
  - filepath
  - HUnit

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

data-files:
- kcsrc/prelude.kc

executables:
  kc:
    source-dirs:      app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main:             Main.hs
    dependencies:
    - KindaC

tests:
  all:
    main: Spec.hs
    source-dirs:
    - test/src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KindaC
    
