resolver: lts-24.4
packages:
- .

extra-deps:
  - ghc-debug-stub-0.7.0.0
  - ghc-debug-convention-0.7.0.0

build:
  # I don't seem to need that?
  #library-profiling: true

  # This one triggers recompilation tho.
  executable-profiling: true
